### ISSUE TITLE
pyqt functionality is limited on MacOS on M1 chips

### ISSUE THREAD

**Issue by WolfHawkeAI** [JS-Produksiyon/pulsar#11]
* File open dialog does not work.
* Cannot paste into text boxes.

**Comment by JSP-JMW** [comment]
This problem was tracked down to being an issue with the way MacOS handles root-level command elevation versus the way Windows handles it. Having to create a more granular approach to how to start up Nebula using MacOS versus the broad sweep of Windows.

To be resolved as **1.0.2**.

**Comment by WolfHawkeAI** [comment]
This has been resolved with a forced restart feature when config file or hosts file settings are to be saved. It works passably well, but will be rather annoying for users. Thanks MacOS for your stupid security impementations!
